import { IPostTemp } from './types';

export const posts: IPostTemp[] = [
  {
    author: 'Марина Левина',
    style: 'Городская классика',
    name: 'villadzh',
    coatings: ['Имитация дерева', 'Имитация камня', 'Матовые'],
    authorUid: 'teXNnj0DXcYd7tKvkbf0Wo3hW5E2',
    text: 'Кухня «Вилладж» – летняя нотка коллекции LORENA! Всеми любимая «Городская классика» расцвела и дополнилась уютными деталями из крашеного натурального дерева: округлыми колоннами, ящиками для специй, резными опорами. Изюминка ансамбля – эффект «шкатулки», его создает теплая натуральная древесина в нишах шкафов. Один раз увидев буфет этой кухни, вы не сможете жить без него: это кладезь ящиков и ящичков, корзин и держателей для бокалов, полочек для специй и соусов – всего, что делает дом дружелюбным и открытым.\n\nЭффект «вкладных фасадов» и фурнитура кухни позволяют отнести ее к представительскому классу. Ручки-ракушки цвета черненого серебра, медная вытяжка и мойка, керамические узорные вставки на смесителе – статусные детали мебели VIII века. Нотки Прованса и благородной английской классики создадут неповторимую гармоничную атмосферу в вашем доме, гармонию Разума и Чувств.\n\nРасчетная длина кухни 2,4 м.\n\nБазовая комплектация включает в себя:\n\nФасады;\nГерметичная столешница (технология AquaLine);\nПетли с доводчиками;\nКороба ЛДСП;\nПлинтус;\nЦоколь;\nВыдвижные элементы;\nСушка;\nМойка и смеситель;\nРучки.',
    title: 'Вилладж',
    images: [
      'https://firebasestorage.googleapis.com/v0/b/react-furniture-52f67.appspot.com/o/blog-posts-img%2Fvilladzh%2F3cf56101f4ce9d23ed9a8c7e987b0c78.webp?alt=media&token=215ca1cf-5734-4433-a32d-e6b8dbea976a',
      'https://firebasestorage.googleapis.com/v0/b/react-furniture-52f67.appspot.com/o/blog-posts-img%2Fvilladzh%2F3w23p23d8yo835x7jbpfhof0zm1gyvy1.webp?alt=media&token=66d05ca4-c392-4f26-80b5-370b1464666a',
      'https://firebasestorage.googleapis.com/v0/b/react-furniture-52f67.appspot.com/o/blog-posts-img%2Fvilladzh%2Faxyk7gaq1n4x0x017ht8m8dwbj6c0w1x.webp?alt=media&token=20b555eb-8e91-4729-b1f0-bbb9d96eee86',
      'https://firebasestorage.googleapis.com/v0/b/react-furniture-52f67.appspot.com/o/blog-posts-img%2Fvilladzh%2Fbf3e89fe47a9aee3e8c7f7195d218b9c.webp?alt=media&token=2ea3772e-f8bf-484c-ace7-707d7ed80484',
      'https://firebasestorage.googleapis.com/v0/b/react-furniture-52f67.appspot.com/o/blog-posts-img%2Fvilladzh%2Fd35da8c8cb80ea9125912afaa208adcd.webp?alt=media&token=19bd4d03-5f2f-4715-a584-4b237636a8df',
      'https://firebasestorage.googleapis.com/v0/b/react-furniture-52f67.appspot.com/o/blog-posts-img%2Fvilladzh%2Fec1adfc753e903481f7871b02347a7e3.webp?alt=media&token=15fa50f2-fb00-4b86-8d70-8b4435fa40b2',
    ],
    comments: [
      {
        author: 'Илья Грачёв',
        text: 'Кухня? похоже на мой зал...\n',
        date: '2022.06.17.22.33',
        avatar:
          'https://lh3.googleusercontent.com/a-/AOh14GjfUIRqlA-Ni_I6VQZYF5wYWT-vW_wXWrTFGkSFjg=s96-c',
        authorUid: 'fv3x1PAuz5O1tEL7Z5DluS9sNQB3',
      },
    ],
    date: '2022.05.01.22.49',
    decor: [
      'Балюстрады',
      'Витражи',
      'Карнизы',
      'Открытые секции',
      'Подзоры',
      'Пилястры',
      'Фрезеровки',
    ],
    id: '2MV4TC8gPc6s1gQ3ETWj',
  },
  {
    name: 'kovado',
    style: 'Городская классика',
    author: 'Марина Левина',
    decor: ['Витражи'],
    coatings: ['Глянцевые', 'Имитация дерева', 'Имитация камня', 'Матовые'],
    images: [
      'https://firebasestorage.googleapis.com/v0/b/react-furniture-52f67.appspot.com/o/blog-posts-img%2Fkovado%2F3d17cac3dc14bc0f8e09ed9daef66231.webp?alt=media&token=1d8ddf51-8462-4eb6-92dc-31a610f8898f',
      'https://firebasestorage.googleapis.com/v0/b/react-furniture-52f67.appspot.com/o/blog-posts-img%2Fkovado%2F3e5qdf2aow5z6fonyitz5jupxpufvzii.webp?alt=media&token=c36948ae-2577-474b-bd17-e26ff5554a81',
      'https://firebasestorage.googleapis.com/v0/b/react-furniture-52f67.appspot.com/o/blog-posts-img%2Fkovado%2F89f030a0c86d3f17e07f1a2e8b62b567.webp?alt=media&token=1270d5ed-3214-4c7e-a78e-1e522c1fdac1',
      'https://firebasestorage.googleapis.com/v0/b/react-furniture-52f67.appspot.com/o/blog-posts-img%2Fkovado%2F172e2660f642bc1d8f06e02a2058c888.webp?alt=media&token=171b76ee-b322-4833-b508-eded22ec5dd0',
      'https://firebasestorage.googleapis.com/v0/b/react-furniture-52f67.appspot.com/o/blog-posts-img%2Fkovado%2F38377c6a41c3dbca6c70766ad2197843.webp?alt=media&token=6a5fa86e-93d0-4e83-90cf-545d361f66e2',
      'https://firebasestorage.googleapis.com/v0/b/react-furniture-52f67.appspot.com/o/blog-posts-img%2Fkovado%2Fcb1cc690d22a09c3df1b7e789df12b7f.webp?alt=media&token=7039875a-61a4-4b11-b9e0-b5cf57c2c2f1',
      'https://firebasestorage.googleapis.com/v0/b/react-furniture-52f67.appspot.com/o/blog-posts-img%2Fkovado%2Ff6b564784bb7dbb0a4fb7158166a2c01.webp?alt=media&token=4a7f48c8-1550-4f30-afc0-781925bdbade',
      'https://firebasestorage.googleapis.com/v0/b/react-furniture-52f67.appspot.com/o/blog-posts-img%2Fkovado%2Flalejaefpx6irk7nbi13c0s36xw03c1m.webp?alt=media&token=5297fae2-5d2f-4a8b-b50b-d036c879867a',
      'https://firebasestorage.googleapis.com/v0/b/react-furniture-52f67.appspot.com/o/blog-posts-img%2Fkovado%2Fpg44fq2jpahcuml7s3c370jtr0faz91z.webp?alt=media&token=38e62349-71d2-4d82-bcde-fb2ccc248d7e',
    ],
    text: 'Гарнитур сделан по канонам итальянской мебели из массива: сборные рамочные фасады, интересная фрезеровка. Однако роль натурального дерева «играет» технологичный материал МДФ с покрытием, имеющим объемную структуру. \n\nПростые строгие формы кухни близки к современному стилю, однако «древесная тема» и очень выразительная текстура материала делают модель весьма привлекательной для любителей классики. В целом уютный, добротный гарнитур «Ковадо» выглядит стильно, дорого и очень натурально.\n\nФасады КОВАДО это сборные рамочные фасады из профилей MDF окутанных 2D плёнкой экошпон. Рамочные детали фасадов имеют соединение «французский запил» (см. фото). Рамка состоит из 4‐х профильных деталей, соединённых при помощи шканто-клеевого соединения, внутри рамки устанавливается филёнка из MDF 6 мм (в цвет деталей рамки) облицованная плёнкой экошпон с двух сторон, стекло 4 мм Прозрачное, Мателюкс, Флекс. Стекло внутри рамки фиксируется гибким разжимным профилем с внутренней стороны фасада.',
    date: '2022.05.01.22.46',
    title: 'Ковадо',
    comments: [],
    authorUid: 'teXNnj0DXcYd7tKvkbf0Wo3hW5E2',
    id: 'nqWU2ct1n6Qq5tzuOU4g',
  },
  {
    comments: [],
    authorUid: 'teXNnj0DXcYd7tKvkbf0Wo3hW5E2',
    title: 'Элегантность носит белые одежды, а утонченность',
    text: 'Светлые фасады в сочетании с простой, ясной и глубокой фрезеровкой дарят покой и умиротворение.\nФасады ЭЛЕГАНТ изготавливаются из MDF 19 мм, покрытой плёнкой ПВХ. Основная фрезеровка, применяемая в данной модели №11. Плёнки, применяемые с фрезеровкой 11, обозначены в перечне материалов.\nПолноценная фрезеровка №11 выполняется на фасадах шириной или высотой 273 мм и больше.\nЕсли ширина или высота фасада составляет 196-272 мм, то выполняется фрезеровка №11 уменьшенного типа. При этом уменьшается ширина рамочной части фасада по сторонам, которые попадают в указанный диапазон (196-272 мм).\nЕсли ширина или высота фасада составляет 146-195, то выполняется фрезеровка №11 упрощённого типа. На фасадах с такой фрезеровкой упрощается форма филёнчатой части фасада и уменьшается рамочная часть в указанном диапазоне (146-195 мм), как на уменьшенной фрезеровке.\nПри ширине или высоте фасада 145 мм и меньше выполняется только окантовочная фрезеровка №35.\nВ модели ЭЛЕГАНТ используются закруглённые элементы – фасады с фрезеровками 11 и 11-2, Минималистичный карниз и подзор.\nВ модели ЭЛЕГАНТ применяются карниз и подзор Минималистичный, пилястры Дек 5.10 и Дек 5.10 цок., декоративные панели Дек 2.8 (см. описания в соответствующих разделах и описания фрезеровок).',
    author: 'Марина Левина',
    name: 'elegantnost-nosit-belie-odezhdi,-a-utonchennost',
    coatings: ['Имитация дерева', 'Имитация камня', 'Имитация металла', 'Матовые'],
    style: 'Городская классика',
    images: [
      'https://firebasestorage.googleapis.com/v0/b/react-furniture-52f67.appspot.com/o/blog-posts-img%2Felegantnost-nosit-belie-odezhdi%2C-a-utonchennost%2F3a8595f6b6a1c7390ced46ba4876efff.webp?alt=media&token=fec77df9-51e9-407a-87b8-1672c4d2736c',
      'https://firebasestorage.googleapis.com/v0/b/react-furniture-52f67.appspot.com/o/blog-posts-img%2Felegantnost-nosit-belie-odezhdi%2C-a-utonchennost%2F71ba28f8aa9fa06d2df406e5da687f10.webp?alt=media&token=77e810ef-b79f-49e2-95a7-f1bf72a5e65f',
      'https://firebasestorage.googleapis.com/v0/b/react-furniture-52f67.appspot.com/o/blog-posts-img%2Felegantnost-nosit-belie-odezhdi%2C-a-utonchennost%2F72c2c195cc9a422e185a5e27b330bd33.webp?alt=media&token=d6f2a121-8245-4a2a-a9d8-19f425bd9fa5',
      'https://firebasestorage.googleapis.com/v0/b/react-furniture-52f67.appspot.com/o/blog-posts-img%2Felegantnost-nosit-belie-odezhdi%2C-a-utonchennost%2F5823b9aa9348db28d65d6beebc5c69e8.webp?alt=media&token=b644cd2d-72cf-4a69-9550-fc11ac463442',
      'https://firebasestorage.googleapis.com/v0/b/react-furniture-52f67.appspot.com/o/blog-posts-img%2Felegantnost-nosit-belie-odezhdi%2C-a-utonchennost%2Facb3f86ae3a39b1c4131e10186155f7b.webp?alt=media&token=d772ca8e-8a2d-4e24-9f70-e7213971f485',
      'https://firebasestorage.googleapis.com/v0/b/react-furniture-52f67.appspot.com/o/blog-posts-img%2Felegantnost-nosit-belie-odezhdi%2C-a-utonchennost%2Fc9b39f33b2f678dfc935a86c88fb211f.webp?alt=media&token=5d17ce96-00f9-4244-b6d7-58d873dc04a1',
      'https://firebasestorage.googleapis.com/v0/b/react-furniture-52f67.appspot.com/o/blog-posts-img%2Felegantnost-nosit-belie-odezhdi%2C-a-utonchennost%2Ff3f7a08131e10a8c6e9315299cd41f0a.webp?alt=media&token=a0458102-e54b-4302-9cc2-2e91968d5991',
      'https://firebasestorage.googleapis.com/v0/b/react-furniture-52f67.appspot.com/o/blog-posts-img%2Felegantnost-nosit-belie-odezhdi%2C-a-utonchennost%2Fjk7u76cwrh0romgbxem0ih4j20mjme3w.webp?alt=media&token=17b5a887-195a-42f6-a00a-5fbb76dd9b11',
    ],
    date: '2022.05.01.21.58',
    decor: [],
    id: 'QLp49sfCqQOC8LdDxCpY',
  },
  {
    coatings: ['Имитация дерева', 'Имитация камня', 'Имитация металла', 'Матовые'],
    authorUid: 'teXNnj0DXcYd7tKvkbf0Wo3hW5E2',
    title: 'Николь – это базовый гардероб кухни',
    text: 'Николь – это базовый гардероб кухни, она гибкая и универсальная, в зависимости от сочетания со столешницей, стеновой и фурнитурой она может предстать в достаточно консервативном свете или в более современном решении. Модель представлена в шести декорах с деликатной текстурой крашеного дерева.\n\nФрезеровка фасадов в новой модели отличается графичностью и чёткостью линий, с одной стороны она может подчеркнуть строгость таких оттенков как Вельвет и Мусс, с другой – нивелировать лёгкость Маренго.\nИндиго – глубокий благородный оттенок, флагман модели. Синий цвет помогает сконцентрироваться и придаёт ясности, не даром цветом 2020 года по версии Pantone стал именно классический синий.\n\nДостаточно подобрать новые аксессуары, антураж и оформление стен. И перед вами уже совсем другая история! Выбрав более сдержанные цвета, карнизы и пилястры –  кухня будет смотреться в более традиционном и классическом стиле.',
    decor: [],
    images: [
      'https://firebasestorage.googleapis.com/v0/b/react-furniture-52f67.appspot.com/o/blog-posts-img%2Fnikol-%E2%80%93-eto-bazovii-garderob-kukhni%2F34865474abf61b34a2f958d64651c3f3.webp?alt=media&token=b0160eb5-ac42-4936-ab08-7d72b4918646',
      'https://firebasestorage.googleapis.com/v0/b/react-furniture-52f67.appspot.com/o/blog-posts-img%2Fnikol-%E2%80%93-eto-bazovii-garderob-kukhni%2Fa7590ce0b80a6f125d604235aa64dd35.webp?alt=media&token=9c1d45c0-9766-4b57-a9ad-5d5cf9981b21',
      'https://firebasestorage.googleapis.com/v0/b/react-furniture-52f67.appspot.com/o/blog-posts-img%2Fnikol-%E2%80%93-eto-bazovii-garderob-kukhni%2Fd6b683c70c6468a1aa2711713525d63d.webp?alt=media&token=28a4ba63-c162-4518-96d5-25eb068954d5',
      'https://firebasestorage.googleapis.com/v0/b/react-furniture-52f67.appspot.com/o/blog-posts-img%2Fnikol-%E2%80%93-eto-bazovii-garderob-kukhni%2Fe13296bef37a44af80ac181ca301b2f4.webp?alt=media&token=7c9d58fa-6f0a-413d-b355-fdfe025d3150',
      'https://firebasestorage.googleapis.com/v0/b/react-furniture-52f67.appspot.com/o/blog-posts-img%2Fnikol-%E2%80%93-eto-bazovii-garderob-kukhni%2Ffsefyngkn7j2nlk0v29r68464t2jt1u3.webp?alt=media&token=1aab2eca-5d1b-495c-b0d5-42b41ac015c6',
      'https://firebasestorage.googleapis.com/v0/b/react-furniture-52f67.appspot.com/o/blog-posts-img%2Fnikol-%E2%80%93-eto-bazovii-garderob-kukhni%2Fusg30kl7mrdzuq8hbokwbj5yzm9us755.webp?alt=media&token=2e330366-2d9d-42ca-935e-65f5470d3138',
    ],
    author: 'Марина Левина',
    comments: [],
    name: 'nikol-–-eto-bazovii-garderob-kukhni',
    style: 'Городская классика',
    date: '2022.05.01.21.55',
    id: 'xQnueMinnK9r421oors4',
  },
  {
    comments: [],
    author: 'Марина Левина',
    style: 'Городская классика',
    authorUid: 'teXNnj0DXcYd7tKvkbf0Wo3hW5E2',
    title: 'МАНЕТТИ - cтрогость и  лаконичность  форм.',
    name: 'manetti---ctrogost-i--lakonichnost--form.',
    images: [
      'https://firebasestorage.googleapis.com/v0/b/react-furniture-52f67.appspot.com/o/blog-posts-img%2Fmanetti---ctrogost-i--lakonichnost--form.%2F7ylzlp0m0p8hpwnrilt9w1l2sbbffweu.webp?alt=media&token=c8e8cf96-d2cd-4294-b85f-88d3e3aaf293',
      'https://firebasestorage.googleapis.com/v0/b/react-furniture-52f67.appspot.com/o/blog-posts-img%2Fmanetti---ctrogost-i--lakonichnost--form.%2F82dcf1ca8eee9c5c66affb3e0ce50277.webp?alt=media&token=bf81ada9-7224-4286-b69a-942bd503d4b2',
      'https://firebasestorage.googleapis.com/v0/b/react-furniture-52f67.appspot.com/o/blog-posts-img%2Fmanetti---ctrogost-i--lakonichnost--form.%2F222kbij1pqntkvpfterwprb2hbqg3yby.webp?alt=media&token=fa20a7e6-bfd6-418a-af07-15863e2ebb7a',
      'https://firebasestorage.googleapis.com/v0/b/react-furniture-52f67.appspot.com/o/blog-posts-img%2Fmanetti---ctrogost-i--lakonichnost--form.%2Faa14dae503258ba991010a55d9b32640.webp?alt=media&token=12135b3b-740f-41b1-a30c-affab2cc3401',
      'https://firebasestorage.googleapis.com/v0/b/react-furniture-52f67.appspot.com/o/blog-posts-img%2Fmanetti---ctrogost-i--lakonichnost--form.%2Fab37bbc7ad8e50231021b3b7ca9bde74.webp?alt=media&token=0df866ac-7cad-4ff6-b760-cbee56d10ca0',
      'https://firebasestorage.googleapis.com/v0/b/react-furniture-52f67.appspot.com/o/blog-posts-img%2Fmanetti---ctrogost-i--lakonichnost--form.%2Ff86b6a5f5890aa385d4e73dadd5bdf28.webp?alt=media&token=4bbecd02-9a38-425e-afd9-6f2dab7ad2f2',
      'https://firebasestorage.googleapis.com/v0/b/react-furniture-52f67.appspot.com/o/blog-posts-img%2Fmanetti---ctrogost-i--lakonichnost--form.%2Fopgcncjq2thkhcw5c9az72um22rsvtjw.webp?alt=media&token=7069a166-ab03-4743-b088-aa321c7ca7f0',
    ],
    decor: [
      'Балюстрады',
      'Витражи',
      'Карнизы',
      'Открытые секции',
      'Подзоры',
      'Пилястры',
      'Фрезеровки',
    ],
    coatings: ['Имитация дерева', 'Имитация камня', 'Матовые'],
    text: 'Долгожданная  новинка  2017  -  модель «МАНЕТТИ» из коллекции Городская классика. Строгость и  лаконичность   форм   ансамбля   создают   атмосферу спокойствия и комфорта. Актуальная  фрезеровка,  оригинальные  витражи  и декоративные элементы позволят  создать  поистине  уникальный  и  модный кухонный гарнитур, который  еще  долго  будет  актуален.\n\nОтличительная   особенность   модели:   широкий  диапазон стилей  от классического  (со  всеми  декоративными  элементами: карниз, подзор,пилястры, балюстрады) до современного (без декоративных элементов).\n\nТекстура фасадов полностью передает текстуру натурального шпона, но не требует специального ухода по сравнению с кухней из массива. \n\nКухня «МАНЕТТИ»  представлена  в двух цветовых решениях на Ваш выбор: «Сальт»  –  покой  и  мягкая  ностальгия;  «Мокко»  – тайна, чистота и постоянство. Оба декора могут сочетаться в одной кухне.',
    date: '2022.05.01.21.53',
    id: '47HcN9vx98Vy33to2DiG',
  },
  {
    date: '2022.05.01.21.49',
    decor: [
      'Балюстрады',
      'Витражи',
      'Карнизы',
      'Открытые секции',
      'Подзоры',
      'Пилястры',
      'Фрезеровки',
    ],
    name: 'britt-–-100-skandinavii-na-vashei-kukhne',
    images: [
      'https://firebasestorage.googleapis.com/v0/b/react-furniture-52f67.appspot.com/o/blog-posts-img%2Fbritt-%E2%80%93-100-skandinavii-na-vashei-kukhne%2F60ihdocxkj89no5ar58c91owsy6d6gtr.webp?alt=media&token=78bb0062-168a-4727-8d9a-debafe06c732',
      'https://firebasestorage.googleapis.com/v0/b/react-furniture-52f67.appspot.com/o/blog-posts-img%2Fbritt-%E2%80%93-100-skandinavii-na-vashei-kukhne%2F812e9c8ccf5181c95f36b1fbaef84b89.webp?alt=media&token=c00716a0-6f8f-4776-a1b7-740ccd6f0d3a',
      'https://firebasestorage.googleapis.com/v0/b/react-furniture-52f67.appspot.com/o/blog-posts-img%2Fbritt-%E2%80%93-100-skandinavii-na-vashei-kukhne%2F372599af97541de27b1500731178e831.webp?alt=media&token=bb3ba9e0-802f-4a9d-84fb-a9eafb0fb594',
      'https://firebasestorage.googleapis.com/v0/b/react-furniture-52f67.appspot.com/o/blog-posts-img%2Fbritt-%E2%80%93-100-skandinavii-na-vashei-kukhne%2Filo25ok4yldruc3p3m6erhzurem0xbu8.webp?alt=media&token=a8d7deac-25e8-4a01-90cb-e34f373593cf',
      'https://firebasestorage.googleapis.com/v0/b/react-furniture-52f67.appspot.com/o/blog-posts-img%2Fbritt-%E2%80%93-100-skandinavii-na-vashei-kukhne%2Fjo857j10es2ex12gaq9w952vm4ilkrri.webp?alt=media&token=d67547b4-6219-46b8-80f6-0d05b34685af',
    ],
    text: 'Бритт - модель датского происхождения, которая стала воплощением скандинавского понятия «хюгге». «Хюгге» - это чувство уюта и комфортного общения с ощущениями благополучия и удовлетворенности. Модель представлена в 5 декорах, легко комбинирующихся между собой. Бритт – это 100% аналог массива. Фасады модели выполнены из ЭКОШПОНА по технологии окутки и абсолютно точно передают текстуру и фактуру дерева с обеих сторон.\n\nОтличительные черты новой модели - это стеллажи в декорах фасадов и фасады с чёрной крашеной филёнкой BlackBoard. Смело оставляйте признания в любви своим близким прямо на кухне. Поверьте, домашние оценят такую заботу!\n\nКухня придётся по вкусу любителям скандинавского стиля и тем, кто предпочитает натуральные материалы, оригинальные и смелые элементы. Тёплые древесные декоры создадут уют на любой кухне даже самой маленькой площади, стилизуют помещение под альпийское шале или авторскую кофейню. Завтракайте, обедайте и ужинайте в стильном месте, не покидая пределов своей квартиры!\n\nВсё, о чём вы мечтали – в одной модели.\nИ это Бритт!',
    coatings: ['Имитация дерева', 'Имитация камня', 'Имитация металла', 'Матовые'],
    style: 'Городская классика',
    title: 'БРИТТ – 100% СКАНДИНАВИИ НА ВАШЕЙ КУХНЕ',
    comments: [],
    author: 'Марина Левина',
    authorUid: 'teXNnj0DXcYd7tKvkbf0Wo3hW5E2',
    id: 'puDC0R8YGZcAfK3VfixO',
  },
  {
    title: 'Венето – это сдержанная и лаконичная классика.',
    text: 'Венето – это сдержанная и лаконичная классика во всем своем великолепии. Новинка от компании LORENA кухни придется по вкусу тем, кто устал от традиционной помпезности и чопорности. Модель прекрасно впишется как в большое пространство дома, так и в маленькую кухню или кухню-гостиную. \n\nВенето – первая модель, изготовленная по технологии «окутки», которая может составить конкуренцию таким признанным хитам продаж, как Нова, Черчилль и Элегант, благодаря лаконичной, но элегантной фрезеровке профиля.\n\nНовинка изготавливается в 5 декорах: Бри, Салер, Талви, Капучино и Рустик. Особую изюминку модели придает модуль под встроенную вытяжку. Его глубина по нижнему краю больше стандартной глубины навесных модулей, за счет этого техника работает эффективнее и выглядит гармоничнее. \n\nМодель Венето может быть дополнена различными декоративными элементами: пилястрами, подзором, карнизом, баллюстрадой, решеткой «Корзинка», вставками «Цветок» или «Птичка», подвесными полками и блоком с фанерными ящиками. В качестве вставок в рамочный профиль предусмотрены стекла: прозрачное, матовое, Флекс и Айс.',
    name: 'veneto-–-eto-sderzhannaya-i-lakonichnaya-klassika.',
    style: 'Городская классика',
    author: 'Марина Левина',
    coatings: ['Имитация дерева', 'Имитация камня', 'Имитация металла', 'Матовые'],
    date: '2022.05.01.21.45',
    authorUid: 'teXNnj0DXcYd7tKvkbf0Wo3hW5E2',
    decor: [
      'Балюстрады',
      'Витражи',
      'Карнизы',
      'Открытые секции',
      'Подзоры',
      'Пилястры',
      'Фрезеровки',
    ],
    images: [
      'https://firebasestorage.googleapis.com/v0/b/react-furniture-52f67.appspot.com/o/blog-posts-img%2Fveneto-%E2%80%93-eto-sderzhannaya-i-lakonichnaya-klassika.%2F4ba57ef2a6f8706fddb93580f70f58d2.webp?alt=media&token=6a68ded3-d877-48a9-b2c5-771f1b5d93ce',
      'https://firebasestorage.googleapis.com/v0/b/react-furniture-52f67.appspot.com/o/blog-posts-img%2Fveneto-%E2%80%93-eto-sderzhannaya-i-lakonichnaya-klassika.%2F9ed9fe8c27cf942dc530ab9f046e6436.webp?alt=media&token=bf143d11-ae32-4419-97ed-743c867307cd',
      'https://firebasestorage.googleapis.com/v0/b/react-furniture-52f67.appspot.com/o/blog-posts-img%2Fveneto-%E2%80%93-eto-sderzhannaya-i-lakonichnaya-klassika.%2F195f3766923037277edad8a6b8aaf460.webp?alt=media&token=22a0d061-b2ef-4759-a2af-bf7462deb211',
      'https://firebasestorage.googleapis.com/v0/b/react-furniture-52f67.appspot.com/o/blog-posts-img%2Fveneto-%E2%80%93-eto-sderzhannaya-i-lakonichnaya-klassika.%2F3365bf60724493e5e950e8c1a2cfc557.webp?alt=media&token=9c3cba36-af45-4572-82fc-bc1c0a49b9eb',
      'https://firebasestorage.googleapis.com/v0/b/react-furniture-52f67.appspot.com/o/blog-posts-img%2Fveneto-%E2%80%93-eto-sderzhannaya-i-lakonichnaya-klassika.%2Fb8afd6a6b3bbbe88d4027564898e166c.webp?alt=media&token=2b5f8000-41c8-428a-bee3-5aa2c9975bcc',
      'https://firebasestorage.googleapis.com/v0/b/react-furniture-52f67.appspot.com/o/blog-posts-img%2Fveneto-%E2%80%93-eto-sderzhannaya-i-lakonichnaya-klassika.%2Fc2f3b6640ab538f5be503a44e2af81d8.webp?alt=media&token=3a72eab5-7390-41a4-94f1-54d4cc5a7c66',
      'https://firebasestorage.googleapis.com/v0/b/react-furniture-52f67.appspot.com/o/blog-posts-img%2Fveneto-%E2%80%93-eto-sderzhannaya-i-lakonichnaya-klassika.%2Fd32185eb297516f8f8631b3e6414b0f9.webp?alt=media&token=e3699438-fa72-4688-898e-a54355ae681e',
      'https://firebasestorage.googleapis.com/v0/b/react-furniture-52f67.appspot.com/o/blog-posts-img%2Fveneto-%E2%80%93-eto-sderzhannaya-i-lakonichnaya-klassika.%2Feb7a1ac0d5c198c66448ee90178e4f90.webp?alt=media&token=de9b26ae-10e7-4d9c-b8d1-b8a3d619f9a6',
    ],
    comments: [],
    id: 'LcoZWW7LTFoIkJnsCyBN',
  },
  {
    author: 'Марина Левина',
    title: 'CANTO –  переворачивает ваше представление о кухне.',
    coatings: ['Имитация дерева', 'Имитация камня', 'Имитация металла', 'Матовые'],
    comments: [],
    images: [
      'https://firebasestorage.googleapis.com/v0/b/react-furniture-52f67.appspot.com/o/blog-posts-img%2Fcanto-%E2%80%93--perevorachivaet-vashe-predstavlenie-o-kukhne.%2F6uik12oe5ym3vzdht68ie1xjjofkc31q.webp?alt=media&token=83572a17-11dd-4e6e-b05a-923253474456',
      'https://firebasestorage.googleapis.com/v0/b/react-furniture-52f67.appspot.com/o/blog-posts-img%2Fcanto-%E2%80%93--perevorachivaet-vashe-predstavlenie-o-kukhne.%2F9b6679ad09d4f9a4d65f5db6ad62b830.webp?alt=media&token=332c14fb-af5a-44fa-9401-1664eb56d833',
      'https://firebasestorage.googleapis.com/v0/b/react-furniture-52f67.appspot.com/o/blog-posts-img%2Fcanto-%E2%80%93--perevorachivaet-vashe-predstavlenie-o-kukhne.%2F62fb9c568688416c56bde454bd659206.webp?alt=media&token=9324ca06-bf8c-40b2-b4f0-29d3b07b6beb',
      'https://firebasestorage.googleapis.com/v0/b/react-furniture-52f67.appspot.com/o/blog-posts-img%2Fcanto-%E2%80%93--perevorachivaet-vashe-predstavlenie-o-kukhne.%2F917bf9edb15d65a69bf526d303e485de.webp?alt=media&token=2942a39b-03c8-44d2-b8d6-8e5977e14bcb',
      'https://firebasestorage.googleapis.com/v0/b/react-furniture-52f67.appspot.com/o/blog-posts-img%2Fcanto-%E2%80%93--perevorachivaet-vashe-predstavlenie-o-kukhne.%2Fcebcaf732cdd1765ecf46f43868b6822.webp?alt=media&token=63e397eb-db28-4f1d-85c9-fa6d10416803',
      'https://firebasestorage.googleapis.com/v0/b/react-furniture-52f67.appspot.com/o/blog-posts-img%2Fcanto-%E2%80%93--perevorachivaet-vashe-predstavlenie-o-kukhne.%2Fcf09f84b5489dabb24751ca7a7ef3647.webp?alt=media&token=0aa8910a-aa21-4c26-9894-8f28111ba24b',
      'https://firebasestorage.googleapis.com/v0/b/react-furniture-52f67.appspot.com/o/blog-posts-img%2Fcanto-%E2%80%93--perevorachivaet-vashe-predstavlenie-o-kukhne.%2Fg5nso1bp02nto7d35p1y4i6rj02can5e.webp?alt=media&token=05f53649-1cae-4986-b236-a3adef36ce33',
    ],
    name: 'canto-–--perevorachivaet-vashe-predstavlenie-o-kukhne.',
    decor: [],
    authorUid: 'teXNnj0DXcYd7tKvkbf0Wo3hW5E2',
    style: 'Городская классика',
    date: '2022.05.01.21.42',
    text: 'CANTO – абсолютная новинка 2019 года, способная перевернуть ваше представление о кухне. Это самая вариативная и многоликая модель за всю историю LORENA кухни. Впервые мы даём возможность выбора филёнки и профиля в разных декорах. \n\nХотите лёгкости и радости бытия? Обратите внимание на женское прочтение модели. Абсолютно «иньская» - мягкая, тёплая и манящая – она создана для хозяйки с лёгким характером. Словно весна CANTO ворвётся в ваш дом и окутает его бесконечным теплом. \n\nБрутальная и контрастная CANTO станет решением для холостяцкой квартиры. «Яньский» хозяин ставит во главу угла современные технические решения и дизайн. \n\nCANTO – инвестиция на годы, где стиль задаёт не кухня, а окружающий её интерьер. Здесь нет ограничений и жёстких привязок. Верны стилю индастриал, лофт или хай-тек? А может не мыслите себя без этно, скандинавского и средиземноморского стилей? CANTO органичен всюду. ',
    id: 'SEZI55UMfDkYOY0vfLq2',
  },
  {
    images: [
      'https://firebasestorage.googleapis.com/v0/b/react-furniture-52f67.appspot.com/o/blog-posts-img%2Falta-%E2%80%93-model-dlya-tekh%2C-kto-tsenit-uyut-i-komfort.%2F49b9fd19824280be2c8788e37223e7f0.webp?alt=media&token=48592bb8-816f-49ef-addb-64fe0e593378',
      'https://firebasestorage.googleapis.com/v0/b/react-furniture-52f67.appspot.com/o/blog-posts-img%2Falta-%E2%80%93-model-dlya-tekh%2C-kto-tsenit-uyut-i-komfort.%2F1737a0fa6cbb97bee5090ae9892b0aa2.webp?alt=media&token=1e392f3a-7deb-4985-a678-9af371ea57c5',
      'https://firebasestorage.googleapis.com/v0/b/react-furniture-52f67.appspot.com/o/blog-posts-img%2Falta-%E2%80%93-model-dlya-tekh%2C-kto-tsenit-uyut-i-komfort.%2Fcc9e3b53b7fbec35eef7ce2258059854.webp?alt=media&token=2d802af9-012b-4bc3-b0be-ebf1452d7af0',
      'https://firebasestorage.googleapis.com/v0/b/react-furniture-52f67.appspot.com/o/blog-posts-img%2Falta-%E2%80%93-model-dlya-tekh%2C-kto-tsenit-uyut-i-komfort.%2Fdf285d2b0188e3dc3644f5d833b00ead.webp?alt=media&token=3b0fd4e1-f519-44cf-a9b0-d65255dad0f3',
    ],
    style: 'Городская классика',
    text: 'Альта – модель для тех, кто ценит уют и комфорт. Сдержанная по своему характеру кухня раскроет свой характер вне зависимости от площади помещения.\n\nВ модели Альта впервые применяется новая разработка LORENA, не имеющая аналогов у российских производителей: ящики для специй с гравировкой. \n\nРасположенные в подвесном модуле, они добавят свежую нотку кухне и создадут ощущение неповторимости интерьера. Просто выберите одно из пяти изображений в стиле «Прованс», а остальное мы сделаем сами!\n\nОбратите внимание насколько легка и открыта Альта. Такой эффект обеспечивает этажерка: завершающий элемент нижней базы сохраняет полезную площадь и при этом не утяжеляет кухню.\n\nВ модели АЛЬТА применяются цоколи MDF 16 мм с плёнкой в цвет фасадов.\nВсе торцы цоколей обрабатываются кромочными лентами ПВХ 0,4 мм близкого\nоттенка (см. Перечень материалов).\n\nВ модели применяются стеновые панели из MDF 16 мм. Торцы панелей\nобрабатываются кромочными лентами ПВХ 0,4 мм близкого оттенка (см. Перечень\nматериалов).\n\nФасады в модели АЛЬТА это сборные рамочные фасады из профилей MDF\nокутанных 2D плёнкой Экошпон. Рамочные детали фасадов имеют классическое\nсоединение с запиливанием профилей под углом 45°. При таком соединении\nдеталей на фасадных деталях не применяются кромочные ленты (т.к. нет видимых\nкоротких торцов профиля). В месте соединения профилей стык между деталями\nполучается малозаметным и почти неосязаемым. Рамка состоит из 4‐х профильных\nдеталей, соединённых при помощи шканто‐клеевого соединения, внутри рамки\nустанавливается филёнка из MDF 6 мм (в цвет деталей рамки) облицованная\nЭкошпоном с двух сторон, либо стекло 4 мм.\n\nМодели АЛЬТА имеет набор декоративных элементов из которых можно\nсоздавать разнотипные кухни. Гарнитур, декорированный карнизом, подзором и\nпилястрами будет иметь более классическое исполнение, а кухня без классических\nатрибутов, но со стеллажными элементами и ванген‐панелями уже будет иметь\nболее современное исполнение.',
    authorUid: 'teXNnj0DXcYd7tKvkbf0Wo3hW5E2',
    name: 'alta-–-model-dlya-tekh,-kto-tsenit-uyut-i-komfort.',
    coatings: ['Имитация дерева', 'Имитация камня', 'Имитация металла', 'Матовые'],
    comments: [],
    date: '2022.05.01.21.09',
    decor: [
      'Балюстрады',
      'Витражи',
      'Карнизы',
      'Открытые секции',
      'Подзоры',
      'Пилястры',
      'Фрезеровки',
    ],
    title: 'Альта – модель для тех, кто ценит уют и комфорт.',
    author: 'Марина Левина',
    id: 'aWEB6GEBfKhu3k87Vmxa',
  },
  {
    date: '2022.05.01.21.04',
    authorUid: 'teXNnj0DXcYd7tKvkbf0Wo3hW5E2',
    style: 'Городская классика',
    text: 'Время обладает необыкновенной силой – оно способно разрушать и… облагораживать предметы интерьера. Мебель, пережившая не один десяток лет, превращается в антиквариат и только вырастает в цене. LORENA кухни представляет вам абсолютную новинку 2019 года – модель «Прованс» с патиной, так изумительно маскирующую силу времени. \n\nКрасивая, изящная и одновременно технологичная кухня с гармоничными, плавными линиями. В её основе лежат французские традиции обстановки деревенского дома и исключительно природные оттенки: ласковый солнечный свет, лавандовое поле, лазурная вода, белые облака и прованская трава. \n\nМы не забыли и о непременном атрибуте стиля – внимание к деталям. Это всевозможные сундучки, шкатулки и ящички: всюду лавандовой нитью протягивается волшебство стиля Прованс.\n\nНовинка от LORENA кухни смотрится легко и нисколько не утяжеляет комнату. В таком интерьере легко дышать, жить и, конечно же, творить кулинарные шедевры!\n\nВ модели ПРОВАНС применяются цоколи MDF 16 мм с плёнкой в цвет фасадов. Все торцы цоколей обрабатываются кромочными лентами ПВХ 0,4 мм близкого оттенка (см. Перечень материалов). В модели применяются стеновые панели из MDF 16 мм. Торцы панелей обрабатываются кромочными лентами ПВХ 0,4 мм близкого оттенка (см. Перечень материалов).',
    decor: [
      'Балюстрады',
      'Витражи',
      'Карнизы',
      'Колонны',
      'Открытые секции',
      'Портал',
      'Подзоры',
      'Пилястры',
      'Фрезеровки',
    ],
    name: 'model-«provans»-s-patinoi,-tak-izumitelno-maskiruyushchuyu-silu-vremeni',
    coatings: ['Имитация дерева', 'Имитация камня', 'Матовые'],
    comments: [],
    author: 'Марина Левина',
    images: [
      'https://firebasestorage.googleapis.com/v0/b/react-furniture-52f67.appspot.com/o/blog-posts-img%2Fmodel-%C2%ABprovans%C2%BB-s-patinoi%2C-tak-izumitelno-maskiruyushchuyu-silu-vremeni%2F2cac6a34ac85caba549c66107323e971.webp?alt=media&token=dbc077a7-c52e-4c6e-bbf6-f2aa503144a0',
      'https://firebasestorage.googleapis.com/v0/b/react-furniture-52f67.appspot.com/o/blog-posts-img%2Fmodel-%C2%ABprovans%C2%BB-s-patinoi%2C-tak-izumitelno-maskiruyushchuyu-silu-vremeni%2F333c6237e06890119a0d0230397acfcb.webp?alt=media&token=81dbf9d6-8c44-465a-b31c-71a6a6a3e71f',
      'https://firebasestorage.googleapis.com/v0/b/react-furniture-52f67.appspot.com/o/blog-posts-img%2Fmodel-%C2%ABprovans%C2%BB-s-patinoi%2C-tak-izumitelno-maskiruyushchuyu-silu-vremeni%2F8703e9fb977f3b97fb5f4c01ada26c3f.webp?alt=media&token=70618f6f-cba2-4a7d-a316-6cd45bfe627d',
      'https://firebasestorage.googleapis.com/v0/b/react-furniture-52f67.appspot.com/o/blog-posts-img%2Fmodel-%C2%ABprovans%C2%BB-s-patinoi%2C-tak-izumitelno-maskiruyushchuyu-silu-vremeni%2Ff7e36878b93d8c428b60feaab7f0b522.webp?alt=media&token=315605e2-46de-4bba-8cb1-5998a77765f0',
    ],
    title: 'Модель «Прованс» с патиной, так изумительно маскирующую силу времени',
    id: 'Ja2XXFOBESGHvQsDqvzA',
  },
  {
    coatings: ['Имитация дерева', 'Имитация камня', 'Имитация металла', 'Матовые'],
    authorUid: 'v9hlFCegOzQFWh98Kk2ZEHcJSfv1',
    author: 'Amiditin',
    decor: ['Витражи'],
    style: 'Городская классика',
    text: 'SAVANNA – первая новинка 2020 года, стильная, деликатная и невероятно модная! \nЭто настоящее воплощение тенденций последних лет, она представлена двумя лаконичными фрезеровками фасадов и четырьмя трендовыми оттенками.\n\nСАВАННА – это образ слияния природы и технологичного  мира.  Чёткие  линии,  выверенная  простота формы, как отражение тренда на лаконичность  и  минимализм  противопоставляются гамме сложных природных оттенков: Фламинго, Бонсай, Муссон и Эму.\nА еще новые мраморные текстуры (Мрамор  Неро и Мрамор Бианко): чёрный и белый мраморы с выразительными крупными прожилками, которые остаются на пике актуальности и в новом сезоне.\n\nСАВАННА – это отражение желания современного человека быть ближе к природе при этом оставаясь в комфортной и привычной ему обстановке.  Новая  модель  –  это  превосходный  симбиоз формы  и  цвета,  отвечающий  потребностям в эстетике и функциональности. Она отлично впишется в разные интерьерные стили, от Сканди до Ар-Деко. \n\nФасады обновлённой модели САВАННА изготавливаются из MDF 19 мм, покрытой плёнкой ПВХ (плёнки, применяемые в модели САВАННА, обозначены в перечне материалов).\n\nТеперь в модели применяется две новые фрезеровки (№ 56 и 57) благодаря чему можно создавать неповторимые кухонные гарнитуры. Весь кухонный гарнитур можно исполнить либо с 56 (56-2 для рамок со стеклом), либо с 57 фрезеровкой (без рамок со стеклом). Кроме этого, в качестве основной фрезеровки можно выбрать, например 56-ю (для напольных модулей и пеналов) и дополнить фрезеровкой 57 в навесных шкафах (либо наоборот). Однако, рекомендуется вверху использовать «лёгкую» 57-ю, а внизу 56-ю фрезеровку с широкой рамкой, при таком сочетании не будет нарушен визуальный баланс, поскольку низ всегда должен быть основательнее верха.',
    title: 'SAVANNA – стильная, деликатная и невероятно модная! ',
    date: '2022.05.01.04.00',
    images: [
      'https://firebasestorage.googleapis.com/v0/b/react-furniture-52f67.appspot.com/o/blog-posts-img%2Fsavanna-%E2%80%93-stilnaya%2C-delikatnaya-i-neveroyatno-modnaya!-%2F2dc74a3c68831e2cc5804234bab5aeaf.webp?alt=media&token=ec681316-fd05-412d-aac6-6e96133f8d6d',
      'https://firebasestorage.googleapis.com/v0/b/react-furniture-52f67.appspot.com/o/blog-posts-img%2Fsavanna-%E2%80%93-stilnaya%2C-delikatnaya-i-neveroyatno-modnaya!-%2F6d2b1999a401708af0f4e5c006e2b0e0.webp?alt=media&token=2556733c-6ffb-454c-a36a-1bdfcbc4f748',
      'https://firebasestorage.googleapis.com/v0/b/react-furniture-52f67.appspot.com/o/blog-posts-img%2Fsavanna-%E2%80%93-stilnaya%2C-delikatnaya-i-neveroyatno-modnaya!-%2F283974ac1ad3323db94ada332fec4893.webp?alt=media&token=19301166-6b80-4e68-be90-b82c300ac90f',
      'https://firebasestorage.googleapis.com/v0/b/react-furniture-52f67.appspot.com/o/blog-posts-img%2Fsavanna-%E2%80%93-stilnaya%2C-delikatnaya-i-neveroyatno-modnaya!-%2Fd13e0c8b2f4f64e105950ed69c56c0f8.webp?alt=media&token=7e775de4-fcba-43e7-b9af-ab6e3ef20f65',
      'https://firebasestorage.googleapis.com/v0/b/react-furniture-52f67.appspot.com/o/blog-posts-img%2Fsavanna-%E2%80%93-stilnaya%2C-delikatnaya-i-neveroyatno-modnaya!-%2Ffbf5eb616feaf485d6495962885ce5c2.webp?alt=media&token=626b3351-b32b-457f-8768-b71c71a749e7',
    ],
    comments: [],
    name: 'savanna-–-stilnaya,-delikatnaya-i-neveroyatno-modnaya!-',
    id: 'zDtFA8ohYkclk2OYYJg5',
  },
  {
    author: 'Amiditin',
    decor: [
      'Балюстрады',
      'Витражи',
      'Карнизы',
      'Открытые секции',
      'Подзоры',
      'Пилястры',
      'Фрезеровки',
    ],
    title: 'Палермо – это современное и свежее прочтение классики',
    authorUid: 'v9hlFCegOzQFWh98Kk2ZEHcJSfv1',
    style: 'Городская классика',
    text: 'Палермо – это современное и свежее прочтение классики. Эта модель идеальна как для классических интерьеров, так и для современных. Благородные матовые поверхности придают особый шарм, глубину и ценность каждому из 8 декоров: Велюр сизый, Велюр серый, Велюр белый, Велюр кремовый, Велюр черничный, Велюр кофейный, Велюр табачный, Велюр лавровый.\n\nОсобенно выразительны фасады Палермо в сочетании с латунной фурнитурой и со светлым камнем и мрамором. Очень актуальна комбинация со светлыми фасадами. Однако также эффектно композиция будет смотреться и в едином цвете, т.к. каждый декор сам по себе привлекателен и самодостаточен! Шелковые на ощупь, фасады Палермо заставят Вас чаще прикасаться к ним и с удовольствием проводить время на новой кухне «Палермо»!\n\nФасады модели ПАЛЕРМО имеют двухслойное строение (изготавливаются из MDF 6 и 16 мм), толщина фасада в рамочной части 19 мм, а в центре 16 мм (на филенчатой части). Фасады покрываются пленками ПВХ. Основная фрезеровка применяемая в данной модели №60. Плёнки, применяемые с фрезеровками серии 60, обозначены в перечне материалов.\n\nМодель ПАЛЕРМО за счет применения или отсутствия декоративных элементов, может быть построена в классическом исполнении (с набором декоративных элементов) или в более современном (без карниза, подзора и пилястр).',
    coatings: ['Имитация камня', 'Матовые'],
    name: 'palermo-–-eto-sovremennoe-i-svezhee-prochtenie-klassiki',
    images: [
      'https://firebasestorage.googleapis.com/v0/b/react-furniture-52f67.appspot.com/o/blog-posts-img%2Fpalermo-%E2%80%93-eto-sovremennoe-i-svezhee-prochtenie-klassiki%2F0f586f92c068b8c74f9af21324695ad0.webp?alt=media&token=2004bbb4-31b5-40d5-8bbc-e8b0c87ec44d',
      'https://firebasestorage.googleapis.com/v0/b/react-furniture-52f67.appspot.com/o/blog-posts-img%2Fpalermo-%E2%80%93-eto-sovremennoe-i-svezhee-prochtenie-klassiki%2F28c9075d0e9d0a031635eb7f404ac83f.webp?alt=media&token=dabc19c6-8810-4e0c-bc3a-13298a978698',
      'https://firebasestorage.googleapis.com/v0/b/react-furniture-52f67.appspot.com/o/blog-posts-img%2Fpalermo-%E2%80%93-eto-sovremennoe-i-svezhee-prochtenie-klassiki%2F54e367d04990358e084037321d155c1f.webp?alt=media&token=8cbcf6af-b505-479b-bf8d-50736883ef51',
      'https://firebasestorage.googleapis.com/v0/b/react-furniture-52f67.appspot.com/o/blog-posts-img%2Fpalermo-%E2%80%93-eto-sovremennoe-i-svezhee-prochtenie-klassiki%2Fbd298e1a8396fe979a0dd7e00431d300%20(1).webp?alt=media&token=a247cfea-b9e6-453b-87d7-fa1ccdae73dd',
      'https://firebasestorage.googleapis.com/v0/b/react-furniture-52f67.appspot.com/o/blog-posts-img%2Fpalermo-%E2%80%93-eto-sovremennoe-i-svezhee-prochtenie-klassiki%2Fbd298e1a8396fe979a0dd7e00431d300.webp?alt=media&token=9b5d9cb0-5ba5-474d-a5ba-a2b3a70623b3',
    ],
    comments: [],
    date: '2022.05.01.02.28',
    id: 'f4UKLpWwObqKbRQqZEfA',
  },
  {
    name: 'myunkhen-–-novinka-2021-goda-tsenitelyam-sovremennogo-stilya.',
    decor: [],
    title: 'Мюнхен – новинка 2021 года ценителям современного стиля.',
    images: [
      'https://firebasestorage.googleapis.com/v0/b/react-furniture-52f67.appspot.com/o/blog-posts-img%2Fmyunkhen-%E2%80%93-novinka-2021-goda-tsenitelyam-sovremennogo-stilya.%2F8c11b5bdf1503cc6a6e9b95249210731.webp?alt=media&token=855bf6bc-465e-4915-92a3-63005a7b9dc1',
      'https://firebasestorage.googleapis.com/v0/b/react-furniture-52f67.appspot.com/o/blog-posts-img%2Fmyunkhen-%E2%80%93-novinka-2021-goda-tsenitelyam-sovremennogo-stilya.%2F73b5dcdf601a51e18e08ec0fd2b9eede.webp?alt=media&token=08c84233-9518-4b4f-ab04-649fb74ef6b8',
      'https://firebasestorage.googleapis.com/v0/b/react-furniture-52f67.appspot.com/o/blog-posts-img%2Fmyunkhen-%E2%80%93-novinka-2021-goda-tsenitelyam-sovremennogo-stilya.%2F2059832c3370296ff1402a5fe8ccd762.webp?alt=media&token=e71ceca0-57c1-43e1-823e-0c9de69e0e89',
      'https://firebasestorage.googleapis.com/v0/b/react-furniture-52f67.appspot.com/o/blog-posts-img%2Fmyunkhen-%E2%80%93-novinka-2021-goda-tsenitelyam-sovremennogo-stilya.%2F4988802615529f92ff9fe7351d1325e9.webp?alt=media&token=33be1e70-bbf3-4019-9125-e3f2dc81c0eb',
      'https://firebasestorage.googleapis.com/v0/b/react-furniture-52f67.appspot.com/o/blog-posts-img%2Fmyunkhen-%E2%80%93-novinka-2021-goda-tsenitelyam-sovremennogo-stilya.%2Facb72fcd3879dccf57fbd7344f007252.webp?alt=media&token=6553d5a5-310e-4452-84c1-52e590a9ac3d',
      'https://firebasestorage.googleapis.com/v0/b/react-furniture-52f67.appspot.com/o/blog-posts-img%2Fmyunkhen-%E2%80%93-novinka-2021-goda-tsenitelyam-sovremennogo-stilya.%2Ffe6365f7152ae622520f06380113801d.webp?alt=media&token=0a8ce7fe-3ff0-4214-b7e9-3aad496d77d7',
    ],
    authorUid: 'v9hlFCegOzQFWh98Kk2ZEHcJSfv1',
    date: '2022.05.01.02.22',
    style: 'Современная коллекция',
    author: 'Amiditin',
    text: 'Представляем новинку 2021 года — модель Studio65 Munich (Мюнхен). Эта модель, как и New York прежде всего адресована ценителям современного стиля.\n\nПродуманный баланс геометрических форм, актуальные древесные поверхности, характерный рисунок мрамора на дополнительной столешнице. В новой модели легко найти элементы для многих актуальных стилевых направлений, что позволит оформить любой интерьер в доме.\n\nВыверенный кратный высотный ряд стеклянных фасадов смотрится невероятно гармонично, создавая в доме лёгкую, воздушную, яркую атмосферу.\n\nБлагодаря своей особой конструкции ручки в Studio65 Munich не выделяются на фоне мебели, создавая нишу за фасадом для его захвата и открывания рукой. То есть, вместо того, чтобы тянуть фасад за ручку, нужно захватывать и тянуть на себя сам фасад.\n\nГлавной особенностью новой модели являются выдвижные фанерные ящики, с отверстием, заменяющим ручку. Фанера, как и любая древесина придает интерьеру мгновенное ощущение теплоты, она превратилась едва ли не в самый модный элемент интерьера. \n\nВ данной модели фанерные ящики имеют финишную отделку НPL древесной текстуры. Сливаясь с интерьером, размывая границы функциональных зон, подчеркнуто экологична и вместе с тем не лишённая шика и своего особого шарма модель Studio65 Munich способна удовлетворить самого взыскательного покупателя.',
    comments: [],
    coatings: ['Имитация дерева', 'Имитация камня', 'Матовые'],
    id: 'G9p3dobpjtP9FUkTqFZq',
  },
  {
    author: 'Amiditin',
    title: 'Космо - новая модель в современном направлении',
    coatings: ['Имитация дерева', 'Имитация камня', 'Матовые'],
    style: 'Современная коллекция',
    date: '2022.05.01.01.21',
    comments: [],
    images: [
      'https://firebasestorage.googleapis.com/v0/b/react-furniture-52f67.appspot.com/o/blog-posts-img%2Fkosmo---novaya-model-v-sovremennom-napravlenii%2F2ee5db79fd0a7e605d2cd36736b55a27.webp?alt=media&token=d15df51d-2c50-43ce-81c6-447b02d37c25',
      'https://firebasestorage.googleapis.com/v0/b/react-furniture-52f67.appspot.com/o/blog-posts-img%2Fkosmo---novaya-model-v-sovremennom-napravlenii%2F3b5ea76a35c2e2ecb2c4d8bd7b3d80ae.webp?alt=media&token=aafe9def-e879-4976-be85-819fb39b967b',
      'https://firebasestorage.googleapis.com/v0/b/react-furniture-52f67.appspot.com/o/blog-posts-img%2Fkosmo---novaya-model-v-sovremennom-napravlenii%2F354f97b97f68e4dad6d8809ac501ea46.webp?alt=media&token=4ae62dc2-52d3-4525-a18a-a91415197a27',
      'https://firebasestorage.googleapis.com/v0/b/react-furniture-52f67.appspot.com/o/blog-posts-img%2Fkosmo---novaya-model-v-sovremennom-napravlenii%2F4048d43b7c9be0127681be6957f71765.webp?alt=media&token=e0e2b4be-3635-4b87-8dcf-34b4ebf23de4',
      'https://firebasestorage.googleapis.com/v0/b/react-furniture-52f67.appspot.com/o/blog-posts-img%2Fkosmo---novaya-model-v-sovremennom-napravlenii%2Facc8ad89999980ae224c4a8944bb5b53.webp?alt=media&token=6b6eb135-7dc1-43d8-99cd-7dd1bb830cef',
      'https://firebasestorage.googleapis.com/v0/b/react-furniture-52f67.appspot.com/o/blog-posts-img%2Fkosmo---novaya-model-v-sovremennom-napravlenii%2Fbdf38403b253b1255621a8b8a250d458.webp?alt=media&token=baaf1854-9527-4ec0-908d-d29a691c7b70',
    ],
    authorUid: 'v9hlFCegOzQFWh98Kk2ZEHcJSfv1',
    name: 'kosmo---novaya-model-v-sovremennom-napravlenii',
    decor: [],
    text: 'Космо - новая модель в современном направлении, линейка «ProDesign».\n\nЭта модель отлично вписывается в помещение «свободной планировки». Она предоставит владельцу проживание в комфортном и уютном пространстве. Помещение может быть оформлено в едином стиле и общей цветовой гамме. Гостиная, холл, кухня, прихожая становятся частями единого открытого пространства, оставаясь при этом отдельными частями.\n\nНовая фрезеровка,  имитирующая наборную доску из реек с проставкой, представлена как в древесных декорах «Дуб темный» и «Дуб натуральный», так и в однотонных «Бланка», «Бонсай» и «Фламинго».\n\nТеплота и благородство древесных декоров создают в доме особую уютную атмосферу. Они актуальны в любые времена. Однотонные же декоры приносят в интерьер современные ноты и лаконичность.',
    id: 'AQFcPn8xPf1Y7q0XBcjZ',
  },
  {
    comments: [
      {
        author: 'Amiditin',
        avatar:
          'https://lh3.googleusercontent.com/a-/AOh14GjXSLC2jpXuPaD1R9QU6W84vE8LH1IdOr9YU5ePDg=s96-c',
        authorUid: 'v9hlFCegOzQFWh98Kk2ZEHcJSfv1',
        date: '2022.05.01.01.12',
        text: 'Спасибо за такую прелесть',
      },
    ],
    coatings: ['Имитация камня', 'Матовые'],
    text: 'Стильная новинка 2021 года в современной коллекции LORENA — модель Студио49 Стокгольм. В звонком и дерзком Стокгольме сочетаются разноразмерные и разноориентируемые фасады, яркие стеллажи оттенка Цитрус и фундаментальные Бетоны: Арт Серый и Арт Белый. Также вместо бетонов можно использовать новые фасады Filmax, подходящим сочетанием будет: Мокрый Асфальт + Кальцит +Цитрус.\n\nСтокгольм, как и вся серия Studio, это больше, чем кухня. Высокие яркие стеллажи, как и фасады Канто со стеклом Дарк Грей и подсветкой в модуле, отлично впишутся в пространство гостиной, а особенно в пространство кухни-гостиной, дополнив кухонный гарнитур.\n\nПредставляем весеннюю новинку 2021 года — модель Studio49 Stockholm (Стокгольм). Эта модель продолжает серию Studio, следуя после Нью-Йорка и Мюнхена, она также входит в линейку ProDesign в коллекции Модерн.\n\nНесмотря на аналогичный Нью-Йорку принцип построения композиции гарнитура, когда сочетаются разноразмерные и разноориентируемые фасады,\nСтокгольм более звонкий и дерзкий. Главной фишкой модели стали яркие стеллажи оттенка Цитрус, который каждый день будет «освещать» помещение воспоминаниями о жарком лете. Живость Цитруса достигается ещё и сочетанием с фундаментальными Бетонами, которые из тренда уже перешли в базу.\n\nЦветовое решение Стокгольма — это воплощение главного сочетания года от Pantone: Ultimate Gray и Illuminating, в качестве первого выступает Арт Бетон Серый, в качестве второго — Цитрус.',
    title: 'Стокгольм — это воплощение главного сочетания года.',
    images: [
      'https://firebasestorage.googleapis.com/v0/b/react-furniture-52f67.appspot.com/o/blog-posts-img%2Fstokgolma-%E2%80%94-eto-voploshchenie-glavnogo-sochetaniya-goda.%2F2d675a4bd58c5cb436398767e2916295.webp?alt=media&token=bdc7b23f-dd37-4680-a07c-d4bf420bdd40',
      'https://firebasestorage.googleapis.com/v0/b/react-furniture-52f67.appspot.com/o/blog-posts-img%2Fstokgolma-%E2%80%94-eto-voploshchenie-glavnogo-sochetaniya-goda.%2F16cc9458395241694ce60d4756491aaf.webp?alt=media&token=d62aee91-6a46-4236-b76c-ba5add03ebb4',
      'https://firebasestorage.googleapis.com/v0/b/react-furniture-52f67.appspot.com/o/blog-posts-img%2Fstokgolma-%E2%80%94-eto-voploshchenie-glavnogo-sochetaniya-goda.%2F97d1a7c0408f18c03f9d47ee3f9363eb.webp?alt=media&token=9426dc4b-bce1-4df5-99ff-596dfe87732b',
      'https://firebasestorage.googleapis.com/v0/b/react-furniture-52f67.appspot.com/o/blog-posts-img%2Fstokgolma-%E2%80%94-eto-voploshchenie-glavnogo-sochetaniya-goda.%2F356017fe03e4ffaffeda4900506776e2.webp?alt=media&token=11ec19d8-35a7-4140-8bda-2aadfb3c0ded',
      'https://firebasestorage.googleapis.com/v0/b/react-furniture-52f67.appspot.com/o/blog-posts-img%2Fstokgolma-%E2%80%94-eto-voploshchenie-glavnogo-sochetaniya-goda.%2Fdf1f128339326754d717e8fce4d1e93b.webp?alt=media&token=dd7d8322-4c33-4e7a-87ee-7433d318323f',
      'https://firebasestorage.googleapis.com/v0/b/react-furniture-52f67.appspot.com/o/blog-posts-img%2Fstokgolma-%E2%80%94-eto-voploshchenie-glavnogo-sochetaniya-goda.%2Fec75792200c428b562c2632793edeb07.webp?alt=media&token=16894705-d517-483e-b2d0-0390a4d76b45',
    ],
    decor: [],
    name: 'stokgolm-—-eto-voploshchenie-glavnogo-sochetaniya-goda.',
    author: 'Amiditin',
    date: '2022.05.01.01.08',
    authorUid: 'v9hlFCegOzQFWh98Kk2ZEHcJSfv1',
    style: 'Современная коллекция',
    id: 'YbmCAvZUlp7kFrZzm1Jv',
  },
  {
    author: 'Amiditin',
    comments: [],
    date: '2022.05.01.01.03',
    coatings: ['Имитация дерева', 'Имитация камня', 'Матовые'],
    authorUid: 'v9hlFCegOzQFWh98Kk2ZEHcJSfv1',
    title: 'NEO — новинка в современном направлении, в линейке “ProDesign”',
    images: [
      'https://firebasestorage.googleapis.com/v0/b/react-furniture-52f67.appspot.com/o/blog-posts-img%2Fneo-%E2%80%94-novinka-v-sovremennom-napravlenii%2C-v-lineike-%E2%80%9Cprodesign%E2%80%9D%2F2e175f13c67963afea65eb41f4bd1894.webp?alt=media&token=07c1bb56-4f6f-452e-911d-798de39f673d',
      'https://firebasestorage.googleapis.com/v0/b/react-furniture-52f67.appspot.com/o/blog-posts-img%2Fneo-%E2%80%94-novinka-v-sovremennom-napravlenii%2C-v-lineike-%E2%80%9Cprodesign%E2%80%9D%2F85306959d236c47511a473f3df03d5b5.webp?alt=media&token=d37a80c5-4345-4c02-99f1-bc4752a71daf',
      'https://firebasestorage.googleapis.com/v0/b/react-furniture-52f67.appspot.com/o/blog-posts-img%2Fneo-%E2%80%94-novinka-v-sovremennom-napravlenii%2C-v-lineike-%E2%80%9Cprodesign%E2%80%9D%2F88498264ff1301b55f2978b20c5ca2f9.webp?alt=media&token=370ddd82-68ca-4d49-94c6-2a00c30157ee',
    ],
    decor: [],
    text: 'NEO - новая модель в современном направлении, линейка ProDesign, которая покорит Вас ультрамодными сочетаниями однотонных и древесных, узких и широких фасадов, профильными ручками и стильными полочками под специи. Neo прекрасно впишется не только в кухню, но и в жилую зону Вашего дома или квартиры и предложит интересные решения для гостиной, кабинета или прихожей. Не нужно отказываться от своей мечты, ведь с Neo можно создать проект практически на любой бюджет.  Это яркий пример, что стильно и современно — не всегда дорого!\n\nNEO отвечает современным тенденциям и наиболее частым запросам потребителя на сегодняшний день.\n\nБудьте верны своему вкусу — именно эта фраза отлично характеризует яркую новинку. Не нужно отказываться от мечты, если кажется, что она не вписывается в бюджет. Выход есть — это NEO.\n\nМатериалы, новые элементы и особенности архитектуры модели позволяют воплотить в жизнь трендовую кухню в рамках даже скромного бюджета. Кроме того NEO будет отличным решением не только для кухни, но и для гостиной, кабинета или детской.',
    name: 'neo-—-novinka-v-sovremennom-napravlenii,-v-lineike-“prodesign”',
    style: 'Современная коллекция',
    id: 'qlZBKDiyJjZN2KlB5uHa',
  },
  {
    decor: [],
    name: 'ernika-–-udivitelnoe-sochetanie-aristokratizma',
    author: 'Amiditin',
    images: [
      'https://firebasestorage.googleapis.com/v0/b/react-furniture-52f67.appspot.com/o/blog-posts-img%2Fernika-%E2%80%93-udivitelnoe-sochetanie-aristokratizma%2F1c48846102d247994f75706795842c60.jpg?alt=media&token=a024d32e-8ff3-4aa4-8808-ac4e341e3e4b',
      'https://firebasestorage.googleapis.com/v0/b/react-furniture-52f67.appspot.com/o/blog-posts-img%2Fernika-%E2%80%93-udivitelnoe-sochetanie-aristokratizma%2F3f83a037656fe29c0370bda7b69157df.jpg?alt=media&token=deb7ffce-5ba3-46cd-b24c-d1b6d738d624',
      'https://firebasestorage.googleapis.com/v0/b/react-furniture-52f67.appspot.com/o/blog-posts-img%2Fernika-%E2%80%93-udivitelnoe-sochetanie-aristokratizma%2F5d2d4bcfcad532dd7a9f199ba01bf1f9.jpg?alt=media&token=c7205fad-e00f-49c7-b7d8-f0b6b0c4c78d',
      'https://firebasestorage.googleapis.com/v0/b/react-furniture-52f67.appspot.com/o/blog-posts-img%2Fernika-%E2%80%93-udivitelnoe-sochetanie-aristokratizma%2F20abab263587d6f9d6b14411b83b150d.jpg?alt=media&token=b1f282b9-16fb-40d2-b1cd-3d227de95eb6',
      'https://firebasestorage.googleapis.com/v0/b/react-furniture-52f67.appspot.com/o/blog-posts-img%2Fernika-%E2%80%93-udivitelnoe-sochetanie-aristokratizma%2F4088acfb766e8dfb5b1fd2642dd4d5dc.jpg?alt=media&token=c7ba141a-d03a-4b0f-913f-161f142287e0',
    ],
    text: 'Дизайнеры фабрики были вдохновлены Итальянской классикой и стремлением вписать ее в современную реальность.\nПолностью повторяя фасады из натурального дерева модель Эрника стоит в 2 раза дешевле аналогичных моделей из массива!\n\nОдной из основных особенностей данной модели считается уникальная возможность создавать собственный стиль.\nТекстуры в данной модели можно комбинировать и создавать свой неповторимый и уникальный кухонный гарнитур. Для данной модели нет стилистических ограничений. Сочетая древесную текстуру фасада со столешницей «Бетон» – мы получаем дерзкий молодежный вариант, а используя все декоративные элементы, сочетая древесные текстуры фасадов и столешницу «Мрамор» - мы добиваемся эффекта классической кухни во всем ее великолепии. \n\nМодель ЭРНИКА представляет собой удивительное сочетание аристократизма, сдержанности и нежности. Эта модель идеально подойдет, как приверженцам классики, которые следуют нормам и традициям, так и поклонникам эклектики. Модель ЭРНИКА поможет создать неповторимый образ для Вашей кухни.\n\nФасады в модели ЭРНИКА это сборные рамочные фасады из профилей MDF\nокутанных 2D плёнкой экошпон. Рамочные детали фасадов имеют классическое\nсоединение с запиливанием профилей под углом 45°. При таком соединении\nдеталей на фасадных деталях не применяются кромочные ленты (т.к. нет видимых\nкоротких торцов профиля). В месте соединения профилей стык между деталями\nполучается малозаметным и почти неосязаемым. Рамка состоит из 4‐х профильных\nдеталей, соединённых при помощи шканто‐клеевого соединения, внутри рамки\nустанавливается фрезерованная филёнка из MDF (в цвет деталей рамки)\nоблицованная плёнкой ПВХ с двух сторон, либо стекло 4 мм.',
    style: 'Классика',
    authorUid: 'v9hlFCegOzQFWh98Kk2ZEHcJSfv1',
    coatings: ['Имитация дерева', 'Имитация камня', 'Матовые'],
    date: '2022.04.29.22.17',
    title: 'Эрника – удивительное сочетание аристократизма',
    comments: [
      {
        author: 'Amiditin',
        authorUid: 'v9hlFCegOzQFWh98Kk2ZEHcJSfv1',
        text: 'Спасибо за такую прелесть!',
        avatar:
          'https://lh3.googleusercontent.com/a-/AOh14GjXSLC2jpXuPaD1R9QU6W84vE8LH1IdOr9YU5ePDg=s96-c',
        date: '2022.04.29.22.21',
      },
      {
        avatar:
          'https://lh3.googleusercontent.com/a-/AOh14GjXSLC2jpXuPaD1R9QU6W84vE8LH1IdOr9YU5ePDg=s96-c',
        text: 'Давно мечтала о новом кухонном гарнитуре, но как-то всё не складывалось. И вот покупка новой квартиры, пришло время исполнять свою мечту. Мы обошли не один салон, смотрели, проектировали, но никак не могли определиться. И только в салоне Лорена мы наконец-то смогли спроектировать именно ту кухню, о которой мечтали. Огромное спасибо менеджеру Екатерине за ее профессионализм, умение услышать пожелания клиента, подсказать. Мы очень долго не могли определиться с цветом, очень нравился цвет Индиго, но мы почему-то боялись, что он будет слишком темным. Но Екатерина нас все-таки уговорила рискнуть, и мы совсем не пожалели, кухня получилась великолепной. В ней все продумано, несмотря на очень небольшой размер помещения, у нас получился гарнитур, в котором хватает места для всей кухонной утвари. Кухню изготовили и установили вовремя. Единственное, после установки мы обнаружили небольшой дефект фасада, но проблему удалось решить, фасад заменили. Выражаем огромную благодарность всем сотрудникам компании Лорена, кто принимал участие в создании нашей кухни. Мы планируем и дальнейшее сотрудничество, уже есть задумки по гардеробной.',
        date: '2022.04.29.22.22',
        author: 'Amiditin',
        authorUid: 'v9hlFCegOzQFWh98Kk2ZEHcJSfv1',
      },
    ],
    id: '5wfzQl5rT8Mc8LpDWZGa',
  },
];
